spring:
  config:
    activate:
      on-profile: test
  main:
    banner-mode: off

  cloud:
    discovery:
      enabled: false

eureka:
  client:
    enabled: false

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN