spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

server:
  port: ${SERVER_PORT}

eureka:
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    jersey:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    loggers:
      enabled: true

logging:
  level:
    root: WARN
    io.envoi: INFO
