spring:
  application:
    name: ${SPRING_APPLICATION_NAME:eureka}

server:
  port: ${SERVER_PORT:8761}

eureka:
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:false}
    jersey:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      probes:
        enabled: true
    loggers:
      enabled: true


logging:
  level:
    root: WARN
    io.envoi: INFO
