spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  web:
    resources:
      add-mappings: false

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webmvc:
          routes:
#            - id: hello-service
#              uri: lb://hello-service
#              predicates:
#                - Path=/hello/**
#              filters:
#                - AddRequestHeader=X-Source-Service, gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    loggers:
      enabled: true

logging:
  level:
    root: WARN
    io.envoi: INFO


server:
  port: ${SERVER_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

