spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  web:
    resources:
      add-mappings: false

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webmvc:
          routes:
#            - id: hello-service
#              uri: lb://hello-service
#              predicates:
#                - Path=/hello/**
#              filters:
#                - AddRequestHeader=X-Source-Service, gateway

server:
  port: ${SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      probes:
        enabled: true
    loggers:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"
  level:
    root: WARN
    io.envoi: INFO
