plugins {
    id 'java-library'
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-dependencies:4.1.0'
    }
}

dependencies {
    implementation 'jakarta.validation:jakarta.validation-api:4.0.0-M1'
    compileOnly 'jakarta.persistence:jakarta.persistence-api'
    compileOnly 'org.hibernate.orm:hibernate-core'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
}