CREATE TABLE profile.media_item_replica
(
    id                   UUID                        NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    title                VARCHAR(255)                NOT NULL,
    cover_url            VARCHAR(255)                        ,
    last_event_id        UUID                        NOT NULL,
    last_event_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted              BOOLEAN                     NOT NULL,
    CONSTRAINT pk_media_item PRIMARY KEY (id)
);

CREATE TABLE profile.user_profile
(
    id                   UUID                        NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    name                 VARCHAR(255)                NOT NULL,
    cover_url            VARCHAR(255)                        ,
    deleted              BOOLEAN                     NOT NULL,
    CONSTRAINT pk_user_profile PRIMARY KEY (id)
);

CREATE TABLE profile.user_folder
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_profile_id      UUID                        NOT NULL,
    name                 VARCHAR(255)                NOT NULL,
    cover_url            VARCHAR(255)                        ,
    position             INT                                 ,
    CONSTRAINT pk_user_folder PRIMARY KEY (id)
);

ALTER TABLE profile.user_folder
    ADD CONSTRAINT FK_USER_PROFILE_ON_FOLDER FOREIGN KEY (user_profile_id) REFERENCES profile.user_profile(id);
